// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package providers

import ()

type Provider struct {
	ID        int32
	Title     string
	Address   string
	Longitude float64
	Latitude  float64
}
